const SOCKET_EVENTS = {
  AUTH: 'AUTH',
  CHAT: 'CHAT',
  READ_CHAT: 'READ_CHAT',
  MEET_NOW: 'MEET_NOW',
  APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
  APPOINTMENT_REMINDER: 'APPOINTMENT_REMINDER',
  APPOINTMENTS: 'APPOINTMENTS',
  MEDICATION_ORDERS: 'MEDICATION_ORDERS',
  PATIENT_NOTES: 'PATIENT_NOTES',
  PATIENT_CAREPLANS: 'PATIENT_CAREPLANS',
  PATIENT_MEDICATION_ORDERS: 'PATIENT_MEDICATION_ORDERS',
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
  ALERTS_UPDATE: 'ALERTS_UPDATE',
  DEVICE_INPUTS_UPDATE: 'DEVICE_INPUTS_UPDATE',
  INVITE_UPDATE: 'INVITE_UPDATE',
  DIRECT_MESSAGES: 'DIRECT_MESSAGES',
  EFAX_MESSAGES: 'EFAX_MESSAGES',
  REPORT_RECORD: 'REPORT_RECORD',
};

export default SOCKET_EVENTS;
